apiVersion: apps/v1
kind: Deployment
metadata:
  name: restful-json-api-golang-deployment
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-api
  template:
    metadata:
      labels:
        app: golang-api
    spec:
      containers:
      - name: restful-json
        image: task1/restful-json-api-golang:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources: 
          limits: 
            cpu: 250m 
            memory: 32Mi
