apiVersion: v1
kind: Service
metadata:
  name: restful-json-api-golang-service
spec:
  selector:
    app: golang-api
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8090
  externalIPs:
    - 192.168.1.101
  